// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwM_qfaWUKnLqdHhC2KPKM4mGdEazXjbQ',
    appId: '1:1017967350226:web:7a51afe821ec936bf4380b',
    messagingSenderId: '1017967350226',
    projectId: 'easy-poker-ad042',
    authDomain: 'easy-poker-ad042.firebaseapp.com',
    storageBucket: 'easy-poker-ad042.appspot.com',
    measurementId: 'G-8Y89Z1DNK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKKqpu-D1wRfKP4LW9y-2T_sZ81wLR3Q',
    appId: '1:1017967350226:android:614944c75dc7d874f4380b',
    messagingSenderId: '1017967350226',
    projectId: 'easy-poker-ad042',
    storageBucket: 'easy-poker-ad042.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYawryiAn-iKJ8aPiaC5MP1IEk-t-ZmIw',
    appId: '1:1017967350226:ios:4c51169a7387c789f4380b',
    messagingSenderId: '1017967350226',
    projectId: 'easy-poker-ad042',
    storageBucket: 'easy-poker-ad042.appspot.com',
    iosBundleId: 'com.example.easyPoker',
  );
}
