name: flutter_build

on:
  workflow_dispatch:
    
jobs:

  build:
    name: get flutter and build
    runs-on: ubuntu-latest
    steps:
    - name: whatever 
      uses: jddeep/Flutter-Runner@56254d611d8b799e297ab6f81ab4ec5dd0d128a2
    - name: build app
      run: |
        echo "build started"
        &&
        flutter pub get
        &&
        flutter build web
        &&
        echo "build done!"
        
        
      
