name: flutter_build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: flutter-cli 
      uses: steebchen/flutter@v1.1.0
    - name: test
      run: echo "test"
                
        
      
