name: flutter_build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: use flutter
      uses: steebchen/flutter@v1.1.0
    - name: build web app
      run: |
          flutter pub get
          &&
          flutter build web
        
                
        
      
