# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: flutter_build

on:
  workflow_dispatch:
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jddeep/Flutter-Runner@56254d611d8b799e297ab6f81ab4ec5dd0d128a2
    - name: build app
      
      run: |
        echo "build started"
        &&
        flutter pub get
        &&
        flutter build web
        &&
        echo "build done!"
        
        
      
